# Q1 Say that we are in a crooked casino where the probability of heads for the biased coin is 3/4, and we observe the following sequence of flips: HTTHH
# Determine whether a fair coin or a biased coin was more likely to have generated this sequence.

B = {'H': 0.75, 'T': 0.25}
F = {'H': 0.5, 'T': 0.5}

B_pr = 1
F_pr = 1
for flip in 'HTTHH':
	B_pr *= B[flip]
	F_pr *= F[flip]


# Q4 Say that we are in a crooked casino where the probability of heads for the biased coin is 3/4.

# Given the sequence of coins π = FBBFF and the sequence of coin flips x = TTHTT, compute the probability Pr(x|π) that this sequence was generated by the given states.

# Round your answer to three decimal places.

def ProbabilityOutcomeGivenPath(x, hidden_path, emission_matrix):
    emission_prob = 1
    for i in range(len(x)):
        emission_prob *= emission_matrix[hidden_path[i]][x[i]]
    return emission_prob

hidden_path = 'FBBFF'
emission_matrix = {'B': {'H': 0.75, 'T': 0.25}, 'F': {'H': 0.5, 'T': 0.5}}
x = 'TTHTT'

round(ProbabilityOutcomeGivenPath(x, hidden_path, emission_matrix), 3)